"""picture field

Revision ID: 6a7e63c1a484
Revises: b80cfd7c359d
Create Date: 2024-06-22 16:59:27.211543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7e63c1a484'
down_revision: Union[str, None] = 'b80cfd7c359d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'picture')
    # ### end Alembic commands ###
